### ISSUE TITLE
Multiple Tables

### ISSUE THREAD

**Issue by mpaul31** [someatoms/jsPDF-AutoTable#10]
i am trying to print out multiple tables but only the first one is showing. do you see anything wrong with the following code?

 angular.forEach($scope.selectedDay.sets, function (set) {
            angular.forEach(set.meals, function (meal) {
                var rows = [];
                angular.forEach(meal.items, function (item) {
                    rows.push({
                        "food": item.food.name,
                        "amount": item.amount,
                        "servingSize": "cup",
                        "protein": "0",
                        "carbs": "0",
                        "fat": "0",
                        "calories": "0"
                    });
                });
                doc.autoTable(cols, rows, { margins: { horizontal: 40, top: 60, bottom: 40 }});
            });
        });

doc.save('table.pdf');

**Comment by mpaul31** [comment]
my margins are also not being applied so maybe something is up in general. here is the whole code

 var doc = new jsPDF('p', 'pt');
        var cols = [
            { title: "Food", key: "food" },
            { title: "Amount", key: "amount" },
            { title: "Serving Size", key: "servingSize" },
            { title: "Protein", key: "protein" },
            { title: "Carbs", key: "carbs" },
            { title: "Fat", key: "fat" },
            { title: "Calories", key: "calories" }
        ];

        doc.setFontSize(20);
        doc.text($scope.selectedDay.name, 40, 48);

        angular.forEach($scope.selectedDay.sets, function (set) {
            angular.forEach(set.meals, function (meal) {
                var rows = [];
                angular.forEach(meal.items, function (item) {
                    rows.push({
                        "food": item.food.name,
                        "amount": item.amount,
                        "servingSize": "cup",
                        "protein": "0",
                        "carbs": "0",
                        "fat": "0",
                        "calories": "0"
                    });
                });
                doc.autoTable(cols, rows, { margins: { horizontal: 40, top: 60, bottom: 40 }});
            });
        });

        doc.save('table.pdf');

**Comment by someatoms** [comment]
Everything seems to be in order, however since you don't specify the startY position of the following tables, they all get printed on the same place. Try changing this line

    doc.autoTable(cols, rows, { margins: { horizontal: 40, top: 60, bottom: 40 }});

into this:

    var endPos = doc.autoTableEndPos();
    doc.autoTable(cols, rows, {
        startY: endPos ? endPos.y + 10 : false,
        margins: {horizontal: 40, top: 60, bottom: 40}
    });

A actually just posted this as an example, check it out in `/examples/examples.js`. I also released version 1.0 a few hours ago so make sure you have the latest version!

**Comment by mpaul31** [comment]
thanks bud will do!

**Comment by mpaul31** [comment]
also a cool feature would to have an autoTableCollection method that took in an array and made sure if the entire table did not fit on the page it would go to the next. damn end users.. :)

**Comment by someatoms** [comment]
Sounded like a good idea! I added an avoidPageSplit option now (version 1.1) which draws the table on a fresh page instead of splitting it up into multiple pages if its height is too long. You can see how it works in the same "Multiple tables" example. I don't think a autoTableCollection method would be a good idea though. That would require the plugin to keep track of the height of custom headers etc which would complicate the api.

**Comment by mpaul31** [comment]
awesome man will try it out! thanks again the plugin is really saving my butt!

**Comment by miteshgcs** [comment]
how can i rotate a big table in jspdf auto table plugin??
