### ISSUE TITLE
Adding Header and Footer to every page in Generated PDF.

### ISSUE THREAD

**Issue by priyankaparihar** [someatoms/jsPDF-AutoTable#3]
I have implemented the pdf generation using jspdf.debug.js. I have tables in the pdf page. Can anyone help me out in adding the header and footer in every page of pdf in case of multiple pages generated for dynamic data.

**Comment by someatoms** [comment]
Headers and footers are now supported! There is an example in `/examples/examples.js` on how to use them.

**Comment by rsrahu3** [comment]
In case if we are adding table one by one in doc,if i use...
  doc.autoTable(getColumns(), getData(40), options1);
for all tables ,pagination is not getting added.Can u pls check nd help me out.

**Comment by simonbengtsson** [comment]
I'm not sure I understand your issue. Could you elaborate in a new issue if you think it is an issue with the plugin or write a question if on stackoverflow?

**Comment by curiousalok** [comment]
@simonbengtsson can you pls help me how to add header footer in jspdf where all pages are generated dynamically and various autotables are used i would like to mention here that doc.addPage() method is not used.
thanks

**Comment by simonbengtsson** [comment]
Checkout the header and footer example or write a question on stackoverflow with more info.

**Comment by curiousalok** [comment]
@simonbengtsson sir.....this is my problem 

I had created a pdf with jspdf () on first page some text are static rest all the data is filled in various autotables..and data is dynamic so pages are generated according to the need of pdf.......the issue i am facing is i have to pace company logo on top of every page and page number on the bottom of every page.......

But i have no idea how to apply logo so that it even shows on the dynamically created pages...


Sir pls help with a working fiddle....thnx
