### ISSUE TITLE
colspan issue

### ISSUE THREAD

**Issue by MarBel78** [someatoms/jsPDF-AutoTable#35]
Hi!, i have a problem with table heads, when there is a colspan included, then there will not print all columns. Thanks for your help !

**Comment by someatoms** [comment]
Hi! That sounds strange. Can you post the code you are using?

**Comment by MarBel78** [comment]
![github](https://cloud.githubusercontent.com/assets/12729273/7957997/b36f31ac-09eb-11e5-9cd9-9c931c621a49.jpg)

**Comment by someatoms** [comment]
After a quick look, I'm not really sure what your issue is. First, the `html to table parser` is very basic and only extracts data from the table.

To set colspan on a row you need to override the `drawCell` function in the options and do something similar to the second `Custom Style` example table. However, colspan is quite complicated to build right now using this plugin so let me know if you have any issues with it. I will make it easier to work with colspan and rowspans in version 2.0 of the library which hopefully will be released in June.

**Comment by someatoms** [comment]
Did you solve your issue?

**Comment by someatoms** [comment]
I'm closing this issue now, feel free to reopen or post another issue if needed.
