### ISSUE TITLE
For Ionic App

### ISSUE THREAD

**Issue by rebelholic** [someatoms/jsPDF-AutoTable#50]
Hello, 

I have problem when making an ionic app with jspdf plugin to generate a PDF file. Before I use this plugin, could this plugin support custom table like [my concept](https://drive.google.com/file/d/0B3s7C6m2GcN8dktVLUlLMDN3blE/view?usp=sharing)?

Thanks before

**Comment by someatoms** [comment]
Hi! Unfortunately this plugin will probably cause you more problem than good. The concept you posted should be easier to make with jspdf alone. I just tried the plugin with ionic however and I had no issues.

**Comment by rebelholic** [comment]
@someatoms Do you have any guide or tutorial make a table with jspdf alone?

**Comment by someatoms** [comment]
No I don't have a guide for that unfortunately, but it should be some guides out there. What I understood from you concept it is rather a document you want to create? 

I would probably make your concept by creating rectangles for the different areas with borders around and then just write text on the appropriate places. You could probably use this plugin to create the price list table, but since it's just a few rows, I would consider just print the text out in a loop and make it look like a table that way, this plugin is a bit overkill for that.
