### ISSUE TITLE
Uncaught TypeError: shrinkableColumns.forEach is not a function

### ISSUE THREAD

**Issue by nithingit** [someatoms/jsPDF-AutoTable#62]
I am creating a table in pdf  document using jspdf autotable.For some of the columns its data  values(text to be displayed inside each cell)are very large,because of this I am getting  Uncaught TypeError: shrinkableColumns.forEach is not a function error at line number 255 of jspdf.plugin.autotable.js file.Since these values could not be accommodated in pdf width.What is the solution to display the rest of the values in the next line if specific width is reached(Automatically wrap).

Thanks

**Comment by someatoms** [comment]
Try to set the style overflow to linebreak. However, your issue is probably not with values being too long. What browser are you using? You might have to polyfill the forEach method if you are using IE8. If you need further assitence it would be good if you can fork the codepen linked in the README and recreate your problem so that I can have a look at the code for your specific issue.

**Comment by someatoms** [comment]
Btw, I don't think you are using the latest version?

**Comment by nithingit** [comment]
I tried setting linebreak to 'overflow' now the pdf is getting generated but the long column values are not displayed fully it is appended with ..(for ex:something...).I want the rest of the values to be displayed in the next line.

**Comment by nithingit** [comment]
yes ,I am using the latest version.

**Comment by nithingit** [comment]
I was setting the column width,I removed it now the issue is resolved.Thanks
